# Task 1.1 Introduction
Iris Dataset

Sneha Sivakaran Modul 12

In [6]:
from sklearn import datasets
import pandas as pd

# Load the iris dataset as a pandas dataframe
iris_X, iris_y = datasets.load_iris(return_X_y=True, as_frame=True)

# Display the first rows
iris_X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
# Function to calculate mean values for all columns of a dataframe
def calcMeans(df):
    means = df.apply(lambda column: column.mean())
    return means

In [8]:
# Calculate the mean values of the iris features
mean_values = calcMeans(iris_X)

mean_values

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [9]:
# Compare results using describe() for validation
iris_X.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000